<?php

use Illuminate\Database\Seeder;
use App\City;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::create(['department_id' =>	2, 'name' =>	'Medellín']);
        City::create(['department_id' =>	2, 'name' =>	'Abejorral']);
        City::create(['department_id' =>	2, 'name' =>	'Abriaquí']);
        City::create(['department_id' =>	2, 'name' =>	'Alejandría']);
        City::create(['department_id' =>	2, 'name' =>	'Amagá']);
        City::create(['department_id' =>	2, 'name' =>	'Amalfi']);
        City::create(['department_id' =>	2, 'name' =>	'Andes']);
        City::create(['department_id' =>	2, 'name' =>	'Angelópolis']);
        City::create(['department_id' =>	2, 'name' =>	'Angostura']);
        City::create(['department_id' =>	2, 'name' =>	'Anorí']);
        City::create(['department_id' =>	2, 'name' =>	'Santafé de Antioquia']);
        City::create(['department_id' =>	2, 'name' =>	'Anza']);
        City::create(['department_id' =>	2, 'name' =>	'Apartadó']);
        City::create(['department_id' =>	2, 'name' =>	'Arboletes']);
        City::create(['department_id' =>	2, 'name' =>	'Argelia']);
        City::create(['department_id' =>	2, 'name' =>	'Armenia']);
        City::create(['department_id' =>	2, 'name' =>	'Barbosa']);
        City::create(['department_id' =>	2, 'name' =>	'Belmira']);
        City::create(['department_id' =>	2, 'name' =>	'Bello']);
        City::create(['department_id' =>	2, 'name' =>	'Betania']);
        City::create(['department_id' =>	2, 'name' =>	'Betulia']);
        City::create(['department_id' =>	2, 'name' =>	'Ciudad Bolívar']);
        City::create(['department_id' =>	2, 'name' =>	'Briceño']);
        City::create(['department_id' =>	2, 'name' =>	'Buriticá']);
        City::create(['department_id' =>	2, 'name' =>	'Cáceres']);
        City::create(['department_id' =>	2, 'name' =>	'Caicedo']);
        City::create(['department_id' =>	2, 'name' =>	'Caldas']);
        City::create(['department_id' =>	2, 'name' =>	'Campamento']);
        City::create(['department_id' =>	2, 'name' =>	'Cañasgordas']);
        City::create(['department_id' =>	2, 'name' =>	'Caracolí']);
        City::create(['department_id' =>	2, 'name' =>	'Caramanta']);
        City::create(['department_id' =>	2, 'name' =>	'Carepa']);
        City::create(['department_id' =>	2, 'name' =>	'El Carmen de Viboral']);
        City::create(['department_id' =>	2, 'name' =>	'Carolina']);
        City::create(['department_id' =>	2, 'name' =>	'Caucasia']);
        City::create(['department_id' =>	2, 'name' =>	'Chigorodó']);
        City::create(['department_id' =>	2, 'name' =>	'Cisneros']);
        City::create(['department_id' =>	2, 'name' =>	'Cocorná']);
        City::create(['department_id' =>	2, 'name' =>	'Concepción']);
        City::create(['department_id' =>	2, 'name' =>	'Concordia']);
        City::create(['department_id' =>	2, 'name' =>	'Copacabana']);
        City::create(['department_id' =>	2, 'name' =>	'Dabeiba']);
        City::create(['department_id' =>	2, 'name' =>	'Don Matías']);
        City::create(['department_id' =>	2, 'name' =>	'Ebéjico']);
        City::create(['department_id' =>	2, 'name' =>	'El Bagre']);
        City::create(['department_id' =>	2, 'name' =>	'Entrerrios']);
        City::create(['department_id' =>	2, 'name' =>	'Envigado']);
        City::create(['department_id' =>	2, 'name' =>	'Fredonia']);
        City::create(['department_id' =>	2, 'name' =>	'Frontino']);
        City::create(['department_id' =>	2, 'name' =>	'Giraldo']);
        City::create(['department_id' =>	2, 'name' =>	'Girardota']);
        City::create(['department_id' =>	2, 'name' =>	'Gómez Plata']);
        City::create(['department_id' =>	2, 'name' =>	'Granada']);
        City::create(['department_id' =>	2, 'name' =>	'Guadalupe']);
        City::create(['department_id' =>	2, 'name' =>	'Guarne']);
        City::create(['department_id' =>	2, 'name' =>	'Guatape']);
        City::create(['department_id' =>	2, 'name' =>	'Heliconia']);
        City::create(['department_id' =>	2, 'name' =>	'Hispania']);
        City::create(['department_id' =>	2, 'name' =>	'Itagui']);
        City::create(['department_id' =>	2, 'name' =>	'Ituango']);
        City::create(['department_id' =>	2, 'name' =>	'Jardín']);
        City::create(['department_id' =>	2, 'name' =>	'Jericó']);
        City::create(['department_id' =>	2, 'name' =>	'La Ceja']);
        City::create(['department_id' =>	2, 'name' =>	'La Estrella']);
        City::create(['department_id' =>	2, 'name' =>	'La Pintada']);
        City::create(['department_id' =>	2, 'name' =>	'La Unión']);
        City::create(['department_id' =>	2, 'name' =>	'Liborina']);
        City::create(['department_id' =>	2, 'name' =>	'Maceo']);
        City::create(['department_id' =>	2, 'name' =>	'Marinilla']);
        City::create(['department_id' =>	2, 'name' =>	'Montebello']);
        City::create(['department_id' =>	2, 'name' =>	'Murindó']);
        City::create(['department_id' =>	2, 'name' =>	'Mutatá']);
        City::create(['department_id' =>	2, 'name' =>	'Nariño']);
        City::create(['department_id' =>	2, 'name' =>	'Necoclí']);
        City::create(['department_id' =>	2, 'name' =>	'Nechí']);
        City::create(['department_id' =>	2, 'name' =>	'Olaya']);
        City::create(['department_id' =>	2, 'name' =>	'Peñol']);
        City::create(['department_id' =>	2, 'name' =>	'Peque']);
        City::create(['department_id' =>	2, 'name' =>	'Pueblorrico']);
        City::create(['department_id' =>	2, 'name' =>	'Puerto Berrío']);
        City::create(['department_id' =>	2, 'name' =>	'Puerto Nare']);
        City::create(['department_id' =>	2, 'name' =>	'Puerto Triunfo']);
        City::create(['department_id' =>	2, 'name' =>	'Remedios']);
        City::create(['department_id' =>	2, 'name' =>	'Retiro']);
        City::create(['department_id' =>	2, 'name' =>	'Rionegro']);
        City::create(['department_id' =>	2, 'name' =>	'Sabanalarga']);
        City::create(['department_id' =>	2, 'name' =>	'Sabaneta']);
        City::create(['department_id' =>	2, 'name' =>	'Salgar']);
        City::create(['department_id' =>	2, 'name' =>	'San Andrés de Cuerquía']);
        City::create(['department_id' =>	2, 'name' =>	'San Carlos']);
        City::create(['department_id' =>	2, 'name' =>	'San Francisco']);
        City::create(['department_id' =>	2, 'name' =>	'San Jerónimo']);
        City::create(['department_id' =>	2, 'name' =>	'San José de la Montaña']);
        City::create(['department_id' =>	2, 'name' =>	'San Juan de Urabá']);
        City::create(['department_id' =>	2, 'name' =>	'San Luis']);
        City::create(['department_id' =>	2, 'name' =>	'San Pedro']);
        City::create(['department_id' =>	2, 'name' =>	'San Pedro de Uraba']);
        City::create(['department_id' =>	2, 'name' =>	'San Rafael']);
        City::create(['department_id' =>	2, 'name' =>	'San Roque']);
        City::create(['department_id' =>	2, 'name' =>	'San Vicente']);
        City::create(['department_id' =>	2, 'name' =>	'Santa Bárbara']);
        City::create(['department_id' =>	2, 'name' =>	'Santa Rosa de Osos']);
        City::create(['department_id' =>	2, 'name' =>	'Santo Domingo']);
        City::create(['department_id' =>	2, 'name' =>	'El Santuario']);
        City::create(['department_id' =>	2, 'name' =>	'Segovia']);
        City::create(['department_id' =>	2, 'name' =>	'Sonson']);
        City::create(['department_id' =>	2, 'name' =>	'Sopetrán']);
        City::create(['department_id' =>	2, 'name' =>	'Támesis']);
        City::create(['department_id' =>	2, 'name' =>	'Tarazá']);
        City::create(['department_id' =>	2, 'name' =>	'Tarso']);
        City::create(['department_id' =>	2, 'name' =>	'Titiribí']);
        City::create(['department_id' =>	2, 'name' =>	'Toledo']);
        City::create(['department_id' =>	2, 'name' =>	'Turbo']);
        City::create(['department_id' =>	2, 'name' =>	'Uramita']);
        City::create(['department_id' =>	2, 'name' =>	'Urrao']);
        City::create(['department_id' =>	2, 'name' =>	'Valdivia']);
        City::create(['department_id' =>	2, 'name' =>	'Valparaíso']);
        City::create(['department_id' =>	2, 'name' =>	'Vegachí']);
        City::create(['department_id' =>	2, 'name' =>	'Venecia']);
        City::create(['department_id' =>	2, 'name' =>	'Vigía del Fuerte']);
        City::create(['department_id' =>	2, 'name' =>	'Yalí']);
        City::create(['department_id' =>	2, 'name' =>	'Yarumal']);
        City::create(['department_id' =>	2, 'name' =>	'Yolombó']);
        City::create(['department_id' =>	2, 'name' =>	'Yondó']);
        City::create(['department_id' =>	2, 'name' =>	'Zaragoza']);
        City::create(['department_id' =>	4, 'name' =>	'Barranquilla']);
        City::create(['department_id' =>	4, 'name' =>	'Baranoa']);
        City::create(['department_id' =>	4, 'name' =>	'Campo de la Cruz']);
        City::create(['department_id' =>	4, 'name' =>	'Candelaria']);
        City::create(['department_id' =>	4, 'name' =>	'Galapa']);
        City::create(['department_id' =>	4, 'name' =>	'Juan de Acosta']);
        City::create(['department_id' =>	4, 'name' =>	'Luruaco']);
        City::create(['department_id' =>	4, 'name' =>	'Malambo']);
        City::create(['department_id' =>	4, 'name' =>	'Manatí']);
        City::create(['department_id' =>	4, 'name' =>	'Palmar de Varela']);
        City::create(['department_id' =>	4, 'name' =>	'Piojó']);
        City::create(['department_id' =>	4, 'name' =>	'Polonuevo']);
        City::create(['department_id' =>	4, 'name' =>	'Ponedera']);
        City::create(['department_id' =>	4, 'name' =>	'Puerto Colombia']);
        City::create(['department_id' =>	4, 'name' =>	'Repelón']);
        City::create(['department_id' =>	4, 'name' =>	'Sabanagrande']);
        City::create(['department_id' =>	4, 'name' =>	'Sabanalarga']);
        City::create(['department_id' =>	4, 'name' =>	'Santa Lucía']);
        City::create(['department_id' =>	4, 'name' =>	'Santo Tomás']);
        City::create(['department_id' =>	4, 'name' =>	'Soledad']);
        City::create(['department_id' =>	4, 'name' =>	'Suan']);
        City::create(['department_id' =>	4, 'name' =>	'Tubará']);
        City::create(['department_id' =>	4, 'name' =>	'Usiacurí']);
        City::create(['department_id' =>	14, 'name' =>	'Bogotá, D.C.']);
        City::create(['department_id' =>	5, 'name' =>	'Cartagena']);
        City::create(['department_id' =>	5, 'name' =>	'Achí']);
        City::create(['department_id' =>	5, 'name' =>	'Altos del Rosario']);
        City::create(['department_id' =>	5, 'name' =>	'Arenal']);
        City::create(['department_id' =>	5, 'name' =>	'Arjona']);
        City::create(['department_id' =>	5, 'name' =>	'Arroyohondo']);
        City::create(['department_id' =>	5, 'name' =>	'Barranco de Loba']);
        City::create(['department_id' =>	5, 'name' =>	'Calamar']);
        City::create(['department_id' =>	5, 'name' =>	'Cantagallo']);
        City::create(['department_id' =>	5, 'name' =>	'Cicuco']);
        City::create(['department_id' =>	5, 'name' =>	'Córdoba']);
        City::create(['department_id' =>	5, 'name' =>	'Clemencia']);
        City::create(['department_id' =>	5, 'name' =>	'El Carmen de Bolívar']);
        City::create(['department_id' =>	5, 'name' =>	'El Guamo']);
        City::create(['department_id' =>	5, 'name' =>	'El Peñón']);
        City::create(['department_id' =>	5, 'name' =>	'Hatillo de Loba']);
        City::create(['department_id' =>	5, 'name' =>	'Magangué']);
        City::create(['department_id' =>	5, 'name' =>	'Mahates']);
        City::create(['department_id' =>	5, 'name' =>	'Margarita']);
        City::create(['department_id' =>	5, 'name' =>	'María la Baja']);
        City::create(['department_id' =>	5, 'name' =>	'Montecristo']);
        City::create(['department_id' =>	5, 'name' =>	'Mompós']);
        City::create(['department_id' =>	5, 'name' =>	'Morales']);
        City::create(['department_id' =>	5, 'name' =>	'Norosí']);
        City::create(['department_id' =>	5, 'name' =>	'Pinillos']);
        City::create(['department_id' =>	5, 'name' =>	'Regidor']);
        City::create(['department_id' =>	5, 'name' =>	'Río Viejo']);
        City::create(['department_id' =>	5, 'name' =>	'San Cristóbal']);
        City::create(['department_id' =>	5, 'name' =>	'San Estanislao']);
        City::create(['department_id' =>	5, 'name' =>	'San Fernando']);
        City::create(['department_id' =>	5, 'name' =>	'San Jacinto']);
        City::create(['department_id' =>	5, 'name' =>	'San Jacinto del Cauca']);
        City::create(['department_id' =>	5, 'name' =>	'San Juan Nepomuceno']);
        City::create(['department_id' =>	5, 'name' =>	'San Martín de Loba']);
        City::create(['department_id' =>	5, 'name' =>	'San Pablo']);
        City::create(['department_id' =>	5, 'name' =>	'Santa Catalina']);
        City::create(['department_id' =>	5, 'name' =>	'Santa Rosa']);
        City::create(['department_id' =>	5, 'name' =>	'Santa Rosa del Sur']);
        City::create(['department_id' =>	5, 'name' =>	'Simití']);
        City::create(['department_id' =>	5, 'name' =>	'Soplaviento']);
        City::create(['department_id' =>	5, 'name' =>	'Talaigua Nuevo']);
        City::create(['department_id' =>	5, 'name' =>	'Tiquisio']);
        City::create(['department_id' =>	5, 'name' =>	'Turbaco']);
        City::create(['department_id' =>	5, 'name' =>	'Turbaná']);
        City::create(['department_id' =>	5, 'name' =>	'Villanueva']);
        City::create(['department_id' =>	5, 'name' =>	'Zambrano']);
        City::create(['department_id' =>	6, 'name' =>	'Tunja']);
        City::create(['department_id' =>	6, 'name' =>	'Almeida']);
        City::create(['department_id' =>	6, 'name' =>	'Aquitania']);
        City::create(['department_id' =>	6, 'name' =>	'Arcabuco']);
        City::create(['department_id' =>	6, 'name' =>	'Belén']);
        City::create(['department_id' =>	6, 'name' =>	'Berbeo']);
        City::create(['department_id' =>	6, 'name' =>	'Betéitiva']);
        City::create(['department_id' =>	6, 'name' =>	'Boavita']);
        City::create(['department_id' =>	6, 'name' =>	'Boyacá']);
        City::create(['department_id' =>	6, 'name' =>	'Briceño']);
        City::create(['department_id' =>	6, 'name' =>	'Buenavista']);
        City::create(['department_id' =>	6, 'name' =>	'Busbanzá']);
        City::create(['department_id' =>	6, 'name' =>	'Caldas']);
        City::create(['department_id' =>	6, 'name' =>	'Campohermoso']);
        City::create(['department_id' =>	6, 'name' =>	'Cerinza']);
        City::create(['department_id' =>	6, 'name' =>	'Chinavita']);
        City::create(['department_id' =>	6, 'name' =>	'Chiquinquirá']);
        City::create(['department_id' =>	6, 'name' =>	'Chiscas']);
        City::create(['department_id' =>	6, 'name' =>	'Chita']);
        City::create(['department_id' =>	6, 'name' =>	'Chitaraque']);
        City::create(['department_id' =>	6, 'name' =>	'Chivatá']);
        City::create(['department_id' =>	6, 'name' =>	'Ciénega']);
        City::create(['department_id' =>	6, 'name' =>	'Cómbita']);
        City::create(['department_id' =>	6, 'name' =>	'Coper']);
        City::create(['department_id' =>	6, 'name' =>	'Corrales']);
        City::create(['department_id' =>	6, 'name' =>	'Covarachía']);
        City::create(['department_id' =>	6, 'name' =>	'Cubará']);
        City::create(['department_id' =>	6, 'name' =>	'Cucaita']);
        City::create(['department_id' =>	6, 'name' =>	'Cuítiva']);
        City::create(['department_id' =>	6, 'name' =>	'Chíquiza']);
        City::create(['department_id' =>	6, 'name' =>	'Chivor']);
        City::create(['department_id' =>	6, 'name' =>	'Duitama']);
        City::create(['department_id' =>	6, 'name' =>	'El Cocuy']);
        City::create(['department_id' =>	6, 'name' =>	'El Espino']);
        City::create(['department_id' =>	6, 'name' =>	'Firavitoba']);
        City::create(['department_id' =>	6, 'name' =>	'Floresta']);
        City::create(['department_id' =>	6, 'name' =>	'Gachantivá']);
        City::create(['department_id' =>	6, 'name' =>	'Gameza']);
        City::create(['department_id' =>	6, 'name' =>	'Garagoa']);
        City::create(['department_id' =>	6, 'name' =>	'Guacamayas']);
        City::create(['department_id' =>	6, 'name' =>	'Guateque']);
        City::create(['department_id' =>	6, 'name' =>	'Guayatá']);
        City::create(['department_id' =>	6, 'name' =>	'Güicán']);
        City::create(['department_id' =>	6, 'name' =>	'Iza']);
        City::create(['department_id' =>	6, 'name' =>	'Jenesano']);
        City::create(['department_id' =>	6, 'name' =>	'Jericó']);
        City::create(['department_id' =>	6, 'name' =>	'Labranzagrande']);
        City::create(['department_id' =>	6, 'name' =>	'La Capilla']);
        City::create(['department_id' =>	6, 'name' =>	'La Victoria']);
        City::create(['department_id' =>	6, 'name' =>	'La Uvita']);
        City::create(['department_id' =>	6, 'name' =>	'Villa de Leyva']);
        City::create(['department_id' =>	6, 'name' =>	'Macanal']);
        City::create(['department_id' =>	6, 'name' =>	'Maripí']);
        City::create(['department_id' =>	6, 'name' =>	'Miraflores']);
        City::create(['department_id' =>	6, 'name' =>	'Mongua']);
        City::create(['department_id' =>	6, 'name' =>	'Monguí']);
        City::create(['department_id' =>	6, 'name' =>	'Moniquirá']);
        City::create(['department_id' =>	6, 'name' =>	'Motavita']);
        City::create(['department_id' =>	6, 'name' =>	'Muzo']);
        City::create(['department_id' =>	6, 'name' =>	'Nobsa']);
        City::create(['department_id' =>	6, 'name' =>	'Nuevo Colón']);
        City::create(['department_id' =>	6, 'name' =>	'Oicatá']);
        City::create(['department_id' =>	6, 'name' =>	'Otanche']);
        City::create(['department_id' =>	6, 'name' =>	'Pachavita']);
        City::create(['department_id' =>	6, 'name' =>	'Páez']);
        City::create(['department_id' =>	6, 'name' =>	'Paipa']);
        City::create(['department_id' =>	6, 'name' =>	'Pajarito']);
        City::create(['department_id' =>	6, 'name' =>	'Panqueba']);
        City::create(['department_id' =>	6, 'name' =>	'Pauna']);
        City::create(['department_id' =>	6, 'name' =>	'Paya']);
        City::create(['department_id' =>	6, 'name' =>	'Paz de Río']);
        City::create(['department_id' =>	6, 'name' =>	'Pesca']);
        City::create(['department_id' =>	6, 'name' =>	'Pisba']);
        City::create(['department_id' =>	6, 'name' =>	'Puerto Boyacá']);
        City::create(['department_id' =>	6, 'name' =>	'Quípama']);
        City::create(['department_id' =>	6, 'name' =>	'Ramiriquí']);
        City::create(['department_id' =>	6, 'name' =>	'Ráquira']);
        City::create(['department_id' =>	6, 'name' =>	'Rondón']);
        City::create(['department_id' =>	6, 'name' =>	'Saboyá']);
        City::create(['department_id' =>	6, 'name' =>	'Sáchica']);
        City::create(['department_id' =>	6, 'name' =>	'Samacá']);
        City::create(['department_id' =>	6, 'name' =>	'San Eduardo']);
        City::create(['department_id' =>	6, 'name' =>	'San José de Pare']);
        City::create(['department_id' =>	6, 'name' =>	'San Luis de Gaceno']);
        City::create(['department_id' =>	6, 'name' =>	'San Mateo']);
        City::create(['department_id' =>	6, 'name' =>	'San Miguel de Sema']);
        City::create(['department_id' =>	6, 'name' =>	'San Pablo de Borbur']);
        City::create(['department_id' =>	6, 'name' =>	'Santana']);
        City::create(['department_id' =>	6, 'name' =>	'Santa María']);
        City::create(['department_id' =>	6, 'name' =>	'Santa Rosa de Viterbo']);
        City::create(['department_id' =>	6, 'name' =>	'Santa Sofía']);
        City::create(['department_id' =>	6, 'name' =>	'Sativanorte']);
        City::create(['department_id' =>	6, 'name' =>	'Sativasur']);
        City::create(['department_id' =>	6, 'name' =>	'Siachoque']);
        City::create(['department_id' =>	6, 'name' =>	'Soatá']);
        City::create(['department_id' =>	6, 'name' =>	'Socotá']);
        City::create(['department_id' =>	6, 'name' =>	'Socha']);
        City::create(['department_id' =>	6, 'name' =>	'Sogamoso']);
        City::create(['department_id' =>	6, 'name' =>	'Somondoco']);
        City::create(['department_id' =>	6, 'name' =>	'Sora']);
        City::create(['department_id' =>	6, 'name' =>	'Sotaquirá']);
        City::create(['department_id' =>	6, 'name' =>	'Soracá']);
        City::create(['department_id' =>	6, 'name' =>	'Susacón']);
        City::create(['department_id' =>	6, 'name' =>	'Sutamarchán']);
        City::create(['department_id' =>	6, 'name' =>	'Sutatenza']);
        City::create(['department_id' =>	6, 'name' =>	'Tasco']);
        City::create(['department_id' =>	6, 'name' =>	'Tenza']);
        City::create(['department_id' =>	6, 'name' =>	'Tibaná']);
        City::create(['department_id' =>	6, 'name' =>	'Tibasosa']);
        City::create(['department_id' =>	6, 'name' =>	'Tinjacá']);
        City::create(['department_id' =>	6, 'name' =>	'Tipacoque']);
        City::create(['department_id' =>	6, 'name' =>	'Toca']);
        City::create(['department_id' =>	6, 'name' =>	'Togüí']);
        City::create(['department_id' =>	6, 'name' =>	'Tópaga']);
        City::create(['department_id' =>	6, 'name' =>	'Tota']);
        City::create(['department_id' =>	6, 'name' =>	'Tununguá']);
        City::create(['department_id' =>	6, 'name' =>	'Turmequé']);
        City::create(['department_id' =>	6, 'name' =>	'Tuta']);
        City::create(['department_id' =>	6, 'name' =>	'Tutazá']);
        City::create(['department_id' =>	6, 'name' =>	'Umbita']);
        City::create(['department_id' =>	6, 'name' =>	'Ventaquemada']);
        City::create(['department_id' =>	6, 'name' =>	'Viracachá']);
        City::create(['department_id' =>	6, 'name' =>	'Zetaquira']);
        City::create(['department_id' =>	7, 'name' =>	'Manizales']);
        City::create(['department_id' =>	7, 'name' =>	'Aguadas']);
        City::create(['department_id' =>	7, 'name' =>	'Anserma']);
        City::create(['department_id' =>	7, 'name' =>	'Aranzazu']);
        City::create(['department_id' =>	7, 'name' =>	'Belalcázar']);
        City::create(['department_id' =>	7, 'name' =>	'Chinchiná']);
        City::create(['department_id' =>	7, 'name' =>	'Filadelfia']);
        City::create(['department_id' =>	7, 'name' =>	'La Dorada']);
        City::create(['department_id' =>	7, 'name' =>	'La Merced']);
        City::create(['department_id' =>	7, 'name' =>	'Manzanares']);
        City::create(['department_id' =>	7, 'name' =>	'Marmato']);
        City::create(['department_id' =>	7, 'name' =>	'Marquetalia']);
        City::create(['department_id' =>	7, 'name' =>	'Marulanda']);
        City::create(['department_id' =>	7, 'name' =>	'Neira']);
        City::create(['department_id' =>	7, 'name' =>	'Norcasia']);
        City::create(['department_id' =>	7, 'name' =>	'Pácora']);
        City::create(['department_id' =>	7, 'name' =>	'Palestina']);
        City::create(['department_id' =>	7, 'name' =>	'Pensilvania']);
        City::create(['department_id' =>	7, 'name' =>	'Riosucio']);
        City::create(['department_id' =>	7, 'name' =>	'Risaralda']);
        City::create(['department_id' =>	7, 'name' =>	'Salamina']);
        City::create(['department_id' =>	7, 'name' =>	'Samaná']);
        City::create(['department_id' =>	7, 'name' =>	'San José']);
        City::create(['department_id' =>	7, 'name' =>	'Supía']);
        City::create(['department_id' =>	7, 'name' =>	'Victoria']);
        City::create(['department_id' =>	7, 'name' =>	'Villamaría']);
        City::create(['department_id' =>	7, 'name' =>	'Viterbo']);
        City::create(['department_id' =>	8, 'name' =>	'Florencia']);
        City::create(['department_id' =>	8, 'name' =>	'Albania']);
        City::create(['department_id' =>	8, 'name' =>	'Belén de los Andaquies']);
        City::create(['department_id' =>	8, 'name' =>	'Cartagena del Chairá']);
        City::create(['department_id' =>	8, 'name' =>	'Curillo']);
        City::create(['department_id' =>	8, 'name' =>	'El Doncello']);
        City::create(['department_id' =>	8, 'name' =>	'El Paujil']);
        City::create(['department_id' =>	8, 'name' =>	'La Montañita']);
        City::create(['department_id' =>	8, 'name' =>	'Milán']);
        City::create(['department_id' =>	8, 'name' =>	'Morelia']);
        City::create(['department_id' =>	8, 'name' =>	'Puerto Rico']);
        City::create(['department_id' =>	8, 'name' =>	'San José del Fragua']);
        City::create(['department_id' =>	8, 'name' =>	'San Vicente del Caguán']);
        City::create(['department_id' =>	8, 'name' =>	'Solano']);
        City::create(['department_id' =>	8, 'name' =>	'Solita']);
        City::create(['department_id' =>	8, 'name' =>	'Valparaíso']);
        City::create(['department_id' =>	10, 'name' =>	'Popayán']);
        City::create(['department_id' =>	10, 'name' =>	'Almaguer']);
        City::create(['department_id' =>	10, 'name' =>	'Argelia']);
        City::create(['department_id' =>	10, 'name' =>	'Balboa']);
        City::create(['department_id' =>	10, 'name' =>	'Bolívar']);
        City::create(['department_id' =>	10, 'name' =>	'Buenos Aires']);
        City::create(['department_id' =>	10, 'name' =>	'Cajibío']);
        City::create(['department_id' =>	10, 'name' =>	'Caldono']);
        City::create(['department_id' =>	10, 'name' =>	'Caloto']);
        City::create(['department_id' =>	10, 'name' =>	'Corinto']);
        City::create(['department_id' =>	10, 'name' =>	'El Tambo']);
        City::create(['department_id' =>	10, 'name' =>	'Florencia']);
        City::create(['department_id' =>	10, 'name' =>	'Guachené']);
        City::create(['department_id' =>	10, 'name' =>	'Guapi']);
        City::create(['department_id' =>	10, 'name' =>	'Inzá']);
        City::create(['department_id' =>	10, 'name' =>	'Jambaló']);
        City::create(['department_id' =>	10, 'name' =>	'La Sierra']);
        City::create(['department_id' =>	10, 'name' =>	'La Vega']);
        City::create(['department_id' =>	10, 'name' =>	'López']);
        City::create(['department_id' =>	10, 'name' =>	'Mercaderes']);
        City::create(['department_id' =>	10, 'name' =>	'Miranda']);
        City::create(['department_id' =>	10, 'name' =>	'Morales']);
        City::create(['department_id' =>	10, 'name' =>	'Padilla']);
        City::create(['department_id' =>	10, 'name' =>	'Paez']);
        City::create(['department_id' =>	10, 'name' =>	'Patía']);
        City::create(['department_id' =>	10, 'name' =>	'Piamonte']);
        City::create(['department_id' =>	10, 'name' =>	'Piendamó']);
        City::create(['department_id' =>	10, 'name' =>	'Puerto Tejada']);
        City::create(['department_id' =>	10, 'name' =>	'Puracé']);
        City::create(['department_id' =>	10, 'name' =>	'Rosas']);
        City::create(['department_id' =>	10, 'name' =>	'San Sebastián']);
        City::create(['department_id' =>	10, 'name' =>	'Santander de Quilichao']);
        City::create(['department_id' =>	10, 'name' =>	'Santa Rosa']);
        City::create(['department_id' =>	10, 'name' =>	'Silvia']);
        City::create(['department_id' =>	10, 'name' =>	'Sotara']);
        City::create(['department_id' =>	10, 'name' =>	'Suárez']);
        City::create(['department_id' =>	10, 'name' =>	'Sucre']);
        City::create(['department_id' =>	10, 'name' =>	'Timbío']);
        City::create(['department_id' =>	10, 'name' =>	'Timbiquí']);
        City::create(['department_id' =>	10, 'name' =>	'Toribio']);
        City::create(['department_id' =>	10, 'name' =>	'Totoró']);
        City::create(['department_id' =>	10, 'name' =>	'Villa Rica']);
        City::create(['department_id' =>	11, 'name' =>	'Valledupar']);
        City::create(['department_id' =>	11, 'name' =>	'Aguachica']);
        City::create(['department_id' =>	11, 'name' =>	'Agustín Codazzi']);
        City::create(['department_id' =>	11, 'name' =>	'Astrea']);
        City::create(['department_id' =>	11, 'name' =>	'Becerril']);
        City::create(['department_id' =>	11, 'name' =>	'Bosconia']);
        City::create(['department_id' =>	11, 'name' =>	'Chimichagua']);
        City::create(['department_id' =>	11, 'name' =>	'Chiriguaná']);
        City::create(['department_id' =>	11, 'name' =>	'Curumaní']);
        City::create(['department_id' =>	11, 'name' =>	'El Copey']);
        City::create(['department_id' =>	11, 'name' =>	'El Paso']);
        City::create(['department_id' =>	11, 'name' =>	'Gamarra']);
        City::create(['department_id' =>	11, 'name' =>	'González']);
        City::create(['department_id' =>	11, 'name' =>	'La Gloria']);
        City::create(['department_id' =>	11, 'name' =>	'La Jagua de Ibirico']);
        City::create(['department_id' =>	11, 'name' =>	'Manaure']);
        City::create(['department_id' =>	11, 'name' =>	'Pailitas']);
        City::create(['department_id' =>	11, 'name' =>	'Pelaya']);
        City::create(['department_id' =>	11, 'name' =>	'Pueblo Bello']);
        City::create(['department_id' =>	11, 'name' =>	'Río de Oro']);
        City::create(['department_id' =>	11, 'name' =>	'La Paz']);
        City::create(['department_id' =>	11, 'name' =>	'San Alberto']);
        City::create(['department_id' =>	11, 'name' =>	'San Diego']);
        City::create(['department_id' =>	11, 'name' =>	'San Martín']);
        City::create(['department_id' =>	11, 'name' =>	'Tamalameque']);
        City::create(['department_id' =>	13, 'name' =>	'Montería']);
        City::create(['department_id' =>	13, 'name' =>	'Ayapel']);
        City::create(['department_id' =>	13, 'name' =>	'Buenavista']);
        City::create(['department_id' =>	13, 'name' =>	'Canalete']);
        City::create(['department_id' =>	13, 'name' =>	'Cereté']);
        City::create(['department_id' =>	13, 'name' =>	'Chimá']);
        City::create(['department_id' =>	13, 'name' =>	'Chinú']);
        City::create(['department_id' =>	13, 'name' =>	'Ciénaga de Oro']);
        City::create(['department_id' =>	13, 'name' =>	'Cotorra']);
        City::create(['department_id' =>	13, 'name' =>	'La Apartada']);
        City::create(['department_id' =>	13, 'name' =>	'Lorica']);
        City::create(['department_id' =>	13, 'name' =>	'Los Córdobas']);
        City::create(['department_id' =>	13, 'name' =>	'Momil']);
        City::create(['department_id' =>	13, 'name' =>	'Montelíbano']);
        City::create(['department_id' =>	13, 'name' =>	'Moñitos']);
        City::create(['department_id' =>	13, 'name' =>	'Planeta Rica']);
        City::create(['department_id' =>	13, 'name' =>	'Pueblo Nuevo']);
        City::create(['department_id' =>	13, 'name' =>	'Puerto Escondido']);
        City::create(['department_id' =>	13, 'name' =>	'Puerto Libertador']);
        City::create(['department_id' =>	13, 'name' =>	'Purísima']);
        City::create(['department_id' =>	13, 'name' =>	'Sahagún']);
        City::create(['department_id' =>	13, 'name' =>	'San Andrés Sotavento']);
        City::create(['department_id' =>	13, 'name' =>	'San Antero']);
        City::create(['department_id' =>	13, 'name' =>	'San Bernardo del Viento']);
        City::create(['department_id' =>	13, 'name' =>	'San Carlos']);
        City::create(['department_id' =>	13, 'name' =>	'San José de Uré']);
        City::create(['department_id' =>	13, 'name' =>	'San Pelayo']);
        City::create(['department_id' =>	13, 'name' =>	'Tierralta']);
        City::create(['department_id' =>	13, 'name' =>	'Tuchín']);
        City::create(['department_id' =>	13, 'name' =>	'Valencia']);
        City::create(['department_id' =>	14, 'name' =>	'Agua de Dios']);
        City::create(['department_id' =>	14, 'name' =>	'Albán']);
        City::create(['department_id' =>	14, 'name' =>	'Anapoima']);
        City::create(['department_id' =>	14, 'name' =>	'Anolaima']);
        City::create(['department_id' =>	14, 'name' =>	'Arbeláez']);
        City::create(['department_id' =>	14, 'name' =>	'Beltrán']);
        City::create(['department_id' =>	14, 'name' =>	'Bituima']);
        City::create(['department_id' =>	14, 'name' =>	'Bojacá']);
        City::create(['department_id' =>	14, 'name' =>	'Cabrera']);
        City::create(['department_id' =>	14, 'name' =>	'Cachipay']);
        City::create(['department_id' =>	14, 'name' =>	'Cajicá']);
        City::create(['department_id' =>	14, 'name' =>	'Caparrapí']);
        City::create(['department_id' =>	14, 'name' =>	'Caqueza']);
        City::create(['department_id' =>	14, 'name' =>	'Carmen de Carupa']);
        City::create(['department_id' =>	14, 'name' =>	'Chaguaní']);
        City::create(['department_id' =>	14, 'name' =>	'Chía']);
        City::create(['department_id' =>	14, 'name' =>	'Chipaque']);
        City::create(['department_id' =>	14, 'name' =>	'Choachí']);
        City::create(['department_id' =>	14, 'name' =>	'Chocontá']);
        City::create(['department_id' =>	14, 'name' =>	'Cogua']);
        City::create(['department_id' =>	14, 'name' =>	'Cota']);
        City::create(['department_id' =>	14, 'name' =>	'Cucunubá']);
        City::create(['department_id' =>	14, 'name' =>	'El Colegio']);
        City::create(['department_id' =>	14, 'name' =>	'El Peñón']);
        City::create(['department_id' =>	14, 'name' =>	'El Rosal']);
        City::create(['department_id' =>	14, 'name' =>	'Facatativá']);
        City::create(['department_id' =>	14, 'name' =>	'Fomeque']);
        City::create(['department_id' =>	14, 'name' =>	'Fosca']);
        City::create(['department_id' =>	14, 'name' =>	'Funza']);
        City::create(['department_id' =>	14, 'name' =>	'Fúquene']);
        City::create(['department_id' =>	14, 'name' =>	'Fusagasugá']);
        City::create(['department_id' =>	14, 'name' =>	'Gachala']);
        City::create(['department_id' =>	14, 'name' =>	'Gachancipá']);
        City::create(['department_id' =>	14, 'name' =>	'Gachetá']);
        City::create(['department_id' =>	14, 'name' =>	'Gama']);
        City::create(['department_id' =>	14, 'name' =>	'Girardot']);
        City::create(['department_id' =>	14, 'name' =>	'Granada']);
        City::create(['department_id' =>	14, 'name' =>	'Guachetá']);
        City::create(['department_id' =>	14, 'name' =>	'Guaduas']);
        City::create(['department_id' =>	14, 'name' =>	'Guasca']);
        City::create(['department_id' =>	14, 'name' =>	'Guataquí']);
        City::create(['department_id' =>	14, 'name' =>	'Guatavita']);
        City::create(['department_id' =>	14, 'name' =>	'Guayabal de Siquima']);
        City::create(['department_id' =>	14, 'name' =>	'Guayabetal']);
        City::create(['department_id' =>	14, 'name' =>	'Gutiérrez']);
        City::create(['department_id' =>	14, 'name' =>	'Jerusalén']);
        City::create(['department_id' =>	14, 'name' =>	'Junín']);
        City::create(['department_id' =>	14, 'name' =>	'La Calera']);
        City::create(['department_id' =>	14, 'name' =>	'La Mesa']);
        City::create(['department_id' =>	14, 'name' =>	'La Palma']);
        City::create(['department_id' =>	14, 'name' =>	'La Peña']);
        City::create(['department_id' =>	14, 'name' =>	'La Vega']);
        City::create(['department_id' =>	14, 'name' =>	'Lenguazaque']);
        City::create(['department_id' =>	14, 'name' =>	'Macheta']);
        City::create(['department_id' =>	14, 'name' =>	'Madrid']);
        City::create(['department_id' =>	14, 'name' =>	'Manta']);
        City::create(['department_id' =>	14, 'name' =>	'Medina']);
        City::create(['department_id' =>	14, 'name' =>	'Mosquera']);
        City::create(['department_id' =>	14, 'name' =>	'Nariño']);
        City::create(['department_id' =>	14, 'name' =>	'Nemocón']);
        City::create(['department_id' =>	14, 'name' =>	'Nilo']);
        City::create(['department_id' =>	14, 'name' =>	'Nimaima']);
        City::create(['department_id' =>	14, 'name' =>	'Nocaima']);
        City::create(['department_id' =>	14, 'name' =>	'Venecia']);
        City::create(['department_id' =>	14, 'name' =>	'Pacho']);
        City::create(['department_id' =>	14, 'name' =>	'Paime']);
        City::create(['department_id' =>	14, 'name' =>	'Pandi']);
        City::create(['department_id' =>	14, 'name' =>	'Paratebueno']);
        City::create(['department_id' =>	14, 'name' =>	'Pasca']);
        City::create(['department_id' =>	14, 'name' =>	'Puerto Salgar']);
        City::create(['department_id' =>	14, 'name' =>	'Pulí']);
        City::create(['department_id' =>	14, 'name' =>	'Quebradanegra']);
        City::create(['department_id' =>	14, 'name' =>	'Quetame']);
        City::create(['department_id' =>	14, 'name' =>	'Quipile']);
        City::create(['department_id' =>	14, 'name' =>	'Apulo']);
        City::create(['department_id' =>	14, 'name' =>	'Ricaurte']);
        City::create(['department_id' =>	14, 'name' =>	'San Antonio del Tequendama']);
        City::create(['department_id' =>	14, 'name' =>	'San Bernardo']);
        City::create(['department_id' =>	14, 'name' =>	'San Cayetano']);
        City::create(['department_id' =>	14, 'name' =>	'San Francisco']);
        City::create(['department_id' =>	14, 'name' =>	'San Juan de Río Seco']);
        City::create(['department_id' =>	14, 'name' =>	'Sasaima']);
        City::create(['department_id' =>	14, 'name' =>	'Sesquilé']);
        City::create(['department_id' =>	14, 'name' =>	'Sibaté']);
        City::create(['department_id' =>	14, 'name' =>	'Silvania']);
        City::create(['department_id' =>	14, 'name' =>	'Simijaca']);
        City::create(['department_id' =>	14, 'name' =>	'Soacha']);
        City::create(['department_id' =>	14, 'name' =>	'Sopó']);
        City::create(['department_id' =>	14, 'name' =>	'Subachoque']);
        City::create(['department_id' =>	14, 'name' =>	'Suesca']);
        City::create(['department_id' =>	14, 'name' =>	'Supatá']);
        City::create(['department_id' =>	14, 'name' =>	'Susa']);
        City::create(['department_id' =>	14, 'name' =>	'Sutatausa']);
        City::create(['department_id' =>	14, 'name' =>	'Tabio']);
        City::create(['department_id' =>	14, 'name' =>	'Tausa']);
        City::create(['department_id' =>	14, 'name' =>	'Tena']);
        City::create(['department_id' =>	14, 'name' =>	'Tenjo']);
        City::create(['department_id' =>	14, 'name' =>	'Tibacuy']);
        City::create(['department_id' =>	14, 'name' =>	'Tibirita']);
        City::create(['department_id' =>	14, 'name' =>	'Tocaima']);
        City::create(['department_id' =>	14, 'name' =>	'Tocancipá']);
        City::create(['department_id' =>	14, 'name' =>	'Topaipí']);
        City::create(['department_id' =>	14, 'name' =>	'Ubalá']);
        City::create(['department_id' =>	14, 'name' =>	'Ubaque']);
        City::create(['department_id' =>	14, 'name' =>	'Villa de San Diego de Ubate']);
        City::create(['department_id' =>	14, 'name' =>	'Une']);
        City::create(['department_id' =>	14, 'name' =>	'Útica']);
        City::create(['department_id' =>	14, 'name' =>	'Vergara']);
        City::create(['department_id' =>	14, 'name' =>	'Vianí']);
        City::create(['department_id' =>	14, 'name' =>	'Villagómez']);
        City::create(['department_id' =>	14, 'name' =>	'Villapinzón']);
        City::create(['department_id' =>	14, 'name' =>	'Villeta']);
        City::create(['department_id' =>	14, 'name' =>	'Viotá']);
        City::create(['department_id' =>	14, 'name' =>	'Yacopí']);
        City::create(['department_id' =>	14, 'name' =>	'Zipacón']);
        City::create(['department_id' =>	14, 'name' =>	'Zipaquirá']);
        City::create(['department_id' =>	12, 'name' =>	'Quibdó']);
        City::create(['department_id' =>	12, 'name' =>	'Acandí']);
        City::create(['department_id' =>	12, 'name' =>	'Alto Baudo']);
        City::create(['department_id' =>	12, 'name' =>	'Atrato']);
        City::create(['department_id' =>	12, 'name' =>	'Bagadó']);
        City::create(['department_id' =>	12, 'name' =>	'Bahía Solano']);
        City::create(['department_id' =>	12, 'name' =>	'Bajo Baudó']);
        City::create(['department_id' =>	12, 'name' =>	'Belén de Bajirá']);
        City::create(['department_id' =>	12, 'name' =>	'Bojaya']);
        City::create(['department_id' =>	12, 'name' =>	'El Cantón del San Pablo']);
        City::create(['department_id' =>	12, 'name' =>	'Carmen del Darien']);
        City::create(['department_id' =>	12, 'name' =>	'Cértegui']);
        City::create(['department_id' =>	12, 'name' =>	'Condoto']);
        City::create(['department_id' =>	12, 'name' =>	'El Carmen de Atrato']);
        City::create(['department_id' =>	12, 'name' =>	'El Litoral del San Juan']);
        City::create(['department_id' =>	12, 'name' =>	'Istmina']);
        City::create(['department_id' =>	12, 'name' =>	'Juradó']);
        City::create(['department_id' =>	12, 'name' =>	'Lloró']);
        City::create(['department_id' =>	12, 'name' =>	'Medio Atrato']);
        City::create(['department_id' =>	12, 'name' =>	'Medio Baudó']);
        City::create(['department_id' =>	12, 'name' =>	'Medio San Juan']);
        City::create(['department_id' =>	12, 'name' =>	'Nóvita']);
        City::create(['department_id' =>	12, 'name' =>	'Nuquí']);
        City::create(['department_id' =>	12, 'name' =>	'Río Iro']);
        City::create(['department_id' =>	12, 'name' =>	'Río Quito']);
        City::create(['department_id' =>	12, 'name' =>	'Riosucio']);
        City::create(['department_id' =>	12, 'name' =>	'San José del Palmar']);
        City::create(['department_id' =>	12, 'name' =>	'Sipí']);
        City::create(['department_id' =>	12, 'name' =>	'Tadó']);
        City::create(['department_id' =>	12, 'name' =>	'Unguía']);
        City::create(['department_id' =>	12, 'name' =>	'Unión Panamericana']);
        City::create(['department_id' =>	17, 'name' =>	'Neiva']);
        City::create(['department_id' =>	17, 'name' =>	'Acevedo']);
        City::create(['department_id' =>	17, 'name' =>	'Agrado']);
        City::create(['department_id' =>	17, 'name' =>	'Aipe']);
        City::create(['department_id' =>	17, 'name' =>	'Algeciras']);
        City::create(['department_id' =>	17, 'name' =>	'Altamira']);
        City::create(['department_id' =>	17, 'name' =>	'Baraya']);
        City::create(['department_id' =>	17, 'name' =>	'Campoalegre']);
        City::create(['department_id' =>	17, 'name' =>	'Colombia']);
        City::create(['department_id' =>	17, 'name' =>	'Elías']);
        City::create(['department_id' =>	17, 'name' =>	'Garzón']);
        City::create(['department_id' =>	17, 'name' =>	'Gigante']);
        City::create(['department_id' =>	17, 'name' =>	'Guadalupe']);
        City::create(['department_id' =>	17, 'name' =>	'Hobo']);
        City::create(['department_id' =>	17, 'name' =>	'Iquira']);
        City::create(['department_id' =>	17, 'name' =>	'Isnos']);
        City::create(['department_id' =>	17, 'name' =>	'La Argentina']);
        City::create(['department_id' =>	17, 'name' =>	'La Plata']);
        City::create(['department_id' =>	17, 'name' =>	'Nátaga']);
        City::create(['department_id' =>	17, 'name' =>	'Oporapa']);
        City::create(['department_id' =>	17, 'name' =>	'Paicol']);
        City::create(['department_id' =>	17, 'name' =>	'Palermo']);
        City::create(['department_id' =>	17, 'name' =>	'Palestina']);
        City::create(['department_id' =>	17, 'name' =>	'Pital']);
        City::create(['department_id' =>	17, 'name' =>	'Pitalito']);
        City::create(['department_id' =>	17, 'name' =>	'Rivera']);
        City::create(['department_id' =>	17, 'name' =>	'Saladoblanco']);
        City::create(['department_id' =>	17, 'name' =>	'San Agustín']);
        City::create(['department_id' =>	17, 'name' =>	'Santa María']);
        City::create(['department_id' =>	17, 'name' =>	'Suaza']);
        City::create(['department_id' =>	17, 'name' =>	'Tarqui']);
        City::create(['department_id' =>	17, 'name' =>	'Tesalia']);
        City::create(['department_id' =>	17, 'name' =>	'Tello']);
        City::create(['department_id' =>	17, 'name' =>	'Teruel']);
        City::create(['department_id' =>	17, 'name' =>	'Timaná']);
        City::create(['department_id' =>	17, 'name' =>	'Villavieja']);
        City::create(['department_id' =>	17, 'name' =>	'Yaguará']);
        City::create(['department_id' =>	18, 'name' =>	'Riohacha']);
        City::create(['department_id' =>	18, 'name' =>	'Albania']);
        City::create(['department_id' =>	18, 'name' =>	'Barrancas']);
        City::create(['department_id' =>	18, 'name' =>	'Dibulla']);
        City::create(['department_id' =>	18, 'name' =>	'Distracción']);
        City::create(['department_id' =>	18, 'name' =>	'El Molino']);
        City::create(['department_id' =>	18, 'name' =>	'Fonseca']);
        City::create(['department_id' =>	18, 'name' =>	'Hatonuevo']);
        City::create(['department_id' =>	18, 'name' =>	'La Jagua del Pilar']);
        City::create(['department_id' =>	18, 'name' =>	'Maicao']);
        City::create(['department_id' =>	18, 'name' =>	'Manaure']);
        City::create(['department_id' =>	18, 'name' =>	'San Juan del Cesar']);
        City::create(['department_id' =>	18, 'name' =>	'Uribia']);
        City::create(['department_id' =>	18, 'name' =>	'Urumita']);
        City::create(['department_id' =>	18, 'name' =>	'Villanueva']);
        City::create(['department_id' =>	19, 'name' =>	'Santa Marta']);
        City::create(['department_id' =>	19, 'name' =>	'Algarrobo']);
        City::create(['department_id' =>	19, 'name' =>	'Aracataca']);
        City::create(['department_id' =>	19, 'name' =>	'Ariguaní']);
        City::create(['department_id' =>	19, 'name' =>	'Cerro San Antonio']);
        City::create(['department_id' =>	19, 'name' =>	'Chibolo']);
        City::create(['department_id' =>	19, 'name' =>	'Ciénaga']);
        City::create(['department_id' =>	19, 'name' =>	'Concordia']);
        City::create(['department_id' =>	19, 'name' =>	'El Banco']);
        City::create(['department_id' =>	19, 'name' =>	'El Piñon']);
        City::create(['department_id' =>	19, 'name' =>	'El Retén']);
        City::create(['department_id' =>	19, 'name' =>	'Fundación']);
        City::create(['department_id' =>	19, 'name' =>	'Guamal']);
        City::create(['department_id' =>	19, 'name' =>	'Nueva Granada']);
        City::create(['department_id' =>	19, 'name' =>	'Pedraza']);
        City::create(['department_id' =>	19, 'name' =>	'Pijiño del Carmen']);
        City::create(['department_id' =>	19, 'name' =>	'Pivijay']);
        City::create(['department_id' =>	19, 'name' =>	'Plato']);
        City::create(['department_id' =>	19, 'name' =>	'Puebloviejo']);
        City::create(['department_id' =>	19, 'name' =>	'Remolino']);
        City::create(['department_id' =>	19, 'name' =>	'Sabanas de San Angel']);
        City::create(['department_id' =>	19, 'name' =>	'Salamina']);
        City::create(['department_id' =>	19, 'name' =>	'San Sebastián de Buenavista']);
        City::create(['department_id' =>	19, 'name' =>	'San Zenón']);
        City::create(['department_id' =>	19, 'name' =>	'Santa Ana']);
        City::create(['department_id' =>	19, 'name' =>	'Santa Bárbara de Pinto']);
        City::create(['department_id' =>	19, 'name' =>	'Sitionuevo']);
        City::create(['department_id' =>	19, 'name' =>	'Tenerife']);
        City::create(['department_id' =>	19, 'name' =>	'Zapayán']);
        City::create(['department_id' =>	19, 'name' =>	'Zona Bananera']);
        City::create(['department_id' =>	20, 'name' =>	'Villavicencio']);
        City::create(['department_id' =>	20, 'name' =>	'Acacías']);
        City::create(['department_id' =>	20, 'name' =>	'Barranca de Upía']);
        City::create(['department_id' =>	20, 'name' =>	'Cabuyaro']);
        City::create(['department_id' =>	20, 'name' =>	'Castilla la Nueva']);
        City::create(['department_id' =>	20, 'name' =>	'Cubarral']);
        City::create(['department_id' =>	20, 'name' =>	'Cumaral']);
        City::create(['department_id' =>	20, 'name' =>	'El Calvario']);
        City::create(['department_id' =>	20, 'name' =>	'El Castillo']);
        City::create(['department_id' =>	20, 'name' =>	'El Dorado']);
        City::create(['department_id' =>	20, 'name' =>	'Fuente de Oro']);
        City::create(['department_id' =>	20, 'name' =>	'Granada']);
        City::create(['department_id' =>	20, 'name' =>	'Guamal']);
        City::create(['department_id' =>	20, 'name' =>	'Mapiripán']);
        City::create(['department_id' =>	20, 'name' =>	'Mesetas']);
        City::create(['department_id' =>	20, 'name' =>	'La Macarena']);
        City::create(['department_id' =>	20, 'name' =>	'Uribe']);
        City::create(['department_id' =>	20, 'name' =>	'Lejanías']);
        City::create(['department_id' =>	20, 'name' =>	'Puerto Concordia']);
        City::create(['department_id' =>	20, 'name' =>	'Puerto Gaitán']);
        City::create(['department_id' =>	20, 'name' =>	'Puerto López']);
        City::create(['department_id' =>	20, 'name' =>	'Puerto Lleras']);
        City::create(['department_id' =>	20, 'name' =>	'Puerto Rico']);
        City::create(['department_id' =>	20, 'name' =>	'Restrepo']);
        City::create(['department_id' =>	20, 'name' =>	'San Carlos de Guaroa']);
        City::create(['department_id' =>	20, 'name' =>	'San Juan de Arama']);
        City::create(['department_id' =>	20, 'name' =>	'San Juanito']);
        City::create(['department_id' =>	20, 'name' =>	'San Martín']);
        City::create(['department_id' =>	20, 'name' =>	'Vistahermosa']);
        City::create(['department_id' =>	21, 'name' =>	'Pasto']);
        City::create(['department_id' =>	21, 'name' =>	'Albán']);
        City::create(['department_id' =>	21, 'name' =>	'Aldana']);
        City::create(['department_id' =>	21, 'name' =>	'Ancuyá']);
        City::create(['department_id' =>	21, 'name' =>	'Arboleda']);
        City::create(['department_id' =>	21, 'name' =>	'Barbacoas']);
        City::create(['department_id' =>	21, 'name' =>	'Belén']);
        City::create(['department_id' =>	21, 'name' =>	'Buesaco']);
        City::create(['department_id' =>	21, 'name' =>	'Colón']);
        City::create(['department_id' =>	21, 'name' =>	'Consaca']);
        City::create(['department_id' =>	21, 'name' =>	'Contadero']);
        City::create(['department_id' =>	21, 'name' =>	'Córdoba']);
        City::create(['department_id' =>	21, 'name' =>	'Cuaspud']);
        City::create(['department_id' =>	21, 'name' =>	'Cumbal']);
        City::create(['department_id' =>	21, 'name' =>	'Cumbitara']);
        City::create(['department_id' =>	21, 'name' =>	'Chachagüí']);
        City::create(['department_id' =>	21, 'name' =>	'El Charco']);
        City::create(['department_id' =>	21, 'name' =>	'El Peñol']);
        City::create(['department_id' =>	21, 'name' =>	'El Rosario']);
        City::create(['department_id' =>	21, 'name' =>	'El Tablón de Gómez']);
        City::create(['department_id' =>	21, 'name' =>	'El Tambo']);
        City::create(['department_id' =>	21, 'name' =>	'Funes']);
        City::create(['department_id' =>	21, 'name' =>	'Guachucal']);
        City::create(['department_id' =>	21, 'name' =>	'Guaitarilla']);
        City::create(['department_id' =>	21, 'name' =>	'Gualmatán']);
        City::create(['department_id' =>	21, 'name' =>	'Iles']);
        City::create(['department_id' =>	21, 'name' =>	'Imués']);
        City::create(['department_id' =>	21, 'name' =>	'Ipiales']);
        City::create(['department_id' =>	21, 'name' =>	'La Cruz']);
        City::create(['department_id' =>	21, 'name' =>	'La Florida']);
        City::create(['department_id' =>	21, 'name' =>	'La Llanada']);
        City::create(['department_id' =>	21, 'name' =>	'La Tola']);
        City::create(['department_id' =>	21, 'name' =>	'La Unión']);
        City::create(['department_id' =>	21, 'name' =>	'Leiva']);
        City::create(['department_id' =>	21, 'name' =>	'Linares']);
        City::create(['department_id' =>	21, 'name' =>	'Los Andes']);
        City::create(['department_id' =>	21, 'name' =>	'Magüi']);
        City::create(['department_id' =>	21, 'name' =>	'Mallama']);
        City::create(['department_id' =>	21, 'name' =>	'Mosquera']);
        City::create(['department_id' =>	21, 'name' =>	'Nariño']);
        City::create(['department_id' =>	21, 'name' =>	'Olaya Herrera']);
        City::create(['department_id' =>	21, 'name' =>	'Ospina']);
        City::create(['department_id' =>	21, 'name' =>	'Francisco Pizarro']);
        City::create(['department_id' =>	21, 'name' =>	'Policarpa']);
        City::create(['department_id' =>	21, 'name' =>	'Potosí']);
        City::create(['department_id' =>	21, 'name' =>	'Providencia']);
        City::create(['department_id' =>	21, 'name' =>	'Puerres']);
        City::create(['department_id' =>	21, 'name' =>	'Pupiales']);
        City::create(['department_id' =>	21, 'name' =>	'Ricaurte']);
        City::create(['department_id' =>	21, 'name' =>	'Roberto Payán']);
        City::create(['department_id' =>	21, 'name' =>	'Samaniego']);
        City::create(['department_id' =>	21, 'name' =>	'Sandoná']);
        City::create(['department_id' =>	21, 'name' =>	'San Bernardo']);
        City::create(['department_id' =>	21, 'name' =>	'San Lorenzo']);
        City::create(['department_id' =>	21, 'name' =>	'San Pablo']);
        City::create(['department_id' =>	21, 'name' =>	'San Pedro de Cartago']);
        City::create(['department_id' =>	21, 'name' =>	'Santa Bárbara']);
        City::create(['department_id' =>	21, 'name' =>	'Santacruz']);
        City::create(['department_id' =>	21, 'name' =>	'Sapuyes']);
        City::create(['department_id' =>	21, 'name' =>	'Taminango']);
        City::create(['department_id' =>	21, 'name' =>	'Tangua']);
        City::create(['department_id' =>	21, 'name' =>	'San Andres de Tumaco']);
        City::create(['department_id' =>	21, 'name' =>	'Túquerres']);
        City::create(['department_id' =>	21, 'name' =>	'Yacuanquer']);
        City::create(['department_id' =>	22, 'name' =>	'Cúcuta']);
        City::create(['department_id' =>	22, 'name' =>	'Abrego']);
        City::create(['department_id' =>	22, 'name' =>	'Arboledas']);
        City::create(['department_id' =>	22, 'name' =>	'Bochalema']);
        City::create(['department_id' =>	22, 'name' =>	'Bucarasica']);
        City::create(['department_id' =>	22, 'name' =>	'Cácota']);
        City::create(['department_id' =>	22, 'name' =>	'Cachirá']);
        City::create(['department_id' =>	22, 'name' =>	'Chinácota']);
        City::create(['department_id' =>	22, 'name' =>	'Chitagá']);
        City::create(['department_id' =>	22, 'name' =>	'Convención']);
        City::create(['department_id' =>	22, 'name' =>	'Cucutilla']);
        City::create(['department_id' =>	22, 'name' =>	'Durania']);
        City::create(['department_id' =>	22, 'name' =>	'El Carmen']);
        City::create(['department_id' =>	22, 'name' =>	'El Tarra']);
        City::create(['department_id' =>	22, 'name' =>	'El Zulia']);
        City::create(['department_id' =>	22, 'name' =>	'Gramalote']);
        City::create(['department_id' =>	22, 'name' =>	'Hacarí']);
        City::create(['department_id' =>	22, 'name' =>	'Herrán']);
        City::create(['department_id' =>	22, 'name' =>	'Labateca']);
        City::create(['department_id' =>	22, 'name' =>	'La Esperanza']);
        City::create(['department_id' =>	22, 'name' =>	'La Playa']);
        City::create(['department_id' =>	22, 'name' =>	'Los Patios']);
        City::create(['department_id' =>	22, 'name' =>	'Lourdes']);
        City::create(['department_id' =>	22, 'name' =>	'Mutiscua']);
        City::create(['department_id' =>	22, 'name' =>	'Ocaña']);
        City::create(['department_id' =>	22, 'name' =>	'Pamplona']);
        City::create(['department_id' =>	22, 'name' =>	'Pamplonita']);
        City::create(['department_id' =>	22, 'name' =>	'Puerto Santander']);
        City::create(['department_id' =>	22, 'name' =>	'Ragonvalia']);
        City::create(['department_id' =>	22, 'name' =>	'Salazar']);
        City::create(['department_id' =>	22, 'name' =>	'San Calixto']);
        City::create(['department_id' =>	22, 'name' =>	'San Cayetano']);
        City::create(['department_id' =>	22, 'name' =>	'Santiago']);
        City::create(['department_id' =>	22, 'name' =>	'Sardinata']);
        City::create(['department_id' =>	22, 'name' =>	'Silos']);
        City::create(['department_id' =>	22, 'name' =>	'Teorama']);
        City::create(['department_id' =>	22, 'name' =>	'Tibú']);
        City::create(['department_id' =>	22, 'name' =>	'Toledo']);
        City::create(['department_id' =>	22, 'name' =>	'Villa Caro']);
        City::create(['department_id' =>	22, 'name' =>	'Villa del Rosario']);
        City::create(['department_id' =>	24, 'name' =>	'Armenia']);
        City::create(['department_id' =>	24, 'name' =>	'Buenavista']);
        City::create(['department_id' =>	24, 'name' =>	'Calarca']);
        City::create(['department_id' =>	24, 'name' =>	'Circasia']);
        City::create(['department_id' =>	24, 'name' =>	'Córdoba']);
        City::create(['department_id' =>	24, 'name' =>	'Filandia']);
        City::create(['department_id' =>	24, 'name' =>	'Génova']);
        City::create(['department_id' =>	24, 'name' =>	'La Tebaida']);
        City::create(['department_id' =>	24, 'name' =>	'Montenegro']);
        City::create(['department_id' =>	24, 'name' =>	'Pijao']);
        City::create(['department_id' =>	24, 'name' =>	'Quimbaya']);
        City::create(['department_id' =>	24, 'name' =>	'Salento']);
        City::create(['department_id' =>	25, 'name' =>	'Pereira']);
        City::create(['department_id' =>	25, 'name' =>	'Apía']);
        City::create(['department_id' =>	25, 'name' =>	'Balboa']);
        City::create(['department_id' =>	25, 'name' =>	'Belén de Umbría']);
        City::create(['department_id' =>	25, 'name' =>	'Dosquebradas']);
        City::create(['department_id' =>	25, 'name' =>	'Guática']);
        City::create(['department_id' =>	25, 'name' =>	'La Celia']);
        City::create(['department_id' =>	25, 'name' =>	'La Virginia']);
        City::create(['department_id' =>	25, 'name' =>	'Marsella']);
        City::create(['department_id' =>	25, 'name' =>	'Mistrató']);
        City::create(['department_id' =>	25, 'name' =>	'Pueblo Rico']);
        City::create(['department_id' =>	25, 'name' =>	'Quinchía']);
        City::create(['department_id' =>	25, 'name' =>	'Santa Rosa de Cabal']);
        City::create(['department_id' =>	25, 'name' =>	'Santuario']);
        City::create(['department_id' =>	27, 'name' =>	'Bucaramanga']);
        City::create(['department_id' =>	27, 'name' =>	'Aguada']);
        City::create(['department_id' =>	27, 'name' =>	'Albania']);
        City::create(['department_id' =>	27, 'name' =>	'Aratoca']);
        City::create(['department_id' =>	27, 'name' =>	'Barbosa']);
        City::create(['department_id' =>	27, 'name' =>	'Barichara']);
        City::create(['department_id' =>	27, 'name' =>	'Barrancabermeja']);
        City::create(['department_id' =>	27, 'name' =>	'Betulia']);
        City::create(['department_id' =>	27, 'name' =>	'Bolívar']);
        City::create(['department_id' =>	27, 'name' =>	'Cabrera']);
        City::create(['department_id' =>	27, 'name' =>	'California']);
        City::create(['department_id' =>	27, 'name' =>	'Capitanejo']);
        City::create(['department_id' =>	27, 'name' =>	'Carcasí']);
        City::create(['department_id' =>	27, 'name' =>	'Cepitá']);
        City::create(['department_id' =>	27, 'name' =>	'Cerrito']);
        City::create(['department_id' =>	27, 'name' =>	'Charalá']);
        City::create(['department_id' =>	27, 'name' =>	'Charta']);
        City::create(['department_id' =>	27, 'name' =>	'Chima']);
        City::create(['department_id' =>	27, 'name' =>	'Chipatá']);
        City::create(['department_id' =>	27, 'name' =>	'Cimitarra']);
        City::create(['department_id' =>	27, 'name' =>	'Concepción']);
        City::create(['department_id' =>	27, 'name' =>	'Confines']);
        City::create(['department_id' =>	27, 'name' =>	'Contratación']);
        City::create(['department_id' =>	27, 'name' =>	'Coromoro']);
        City::create(['department_id' =>	27, 'name' =>	'Curití']);
        City::create(['department_id' =>	27, 'name' =>	'El Carmen de Chucurí']);
        City::create(['department_id' =>	27, 'name' =>	'El Guacamayo']);
        City::create(['department_id' =>	27, 'name' =>	'El Peñón']);
        City::create(['department_id' =>	27, 'name' =>	'El Playón']);
        City::create(['department_id' =>	27, 'name' =>	'Encino']);
        City::create(['department_id' =>	27, 'name' =>	'Enciso']);
        City::create(['department_id' =>	27, 'name' =>	'Florián']);
        City::create(['department_id' =>	27, 'name' =>	'Floridablanca']);
        City::create(['department_id' =>	27, 'name' =>	'Galán']);
        City::create(['department_id' =>	27, 'name' =>	'Gambita']);
        City::create(['department_id' =>	27, 'name' =>	'Girón']);
        City::create(['department_id' =>	27, 'name' =>	'Guaca']);
        City::create(['department_id' =>	27, 'name' =>	'Guadalupe']);
        City::create(['department_id' =>	27, 'name' =>	'Guapotá']);
        City::create(['department_id' =>	27, 'name' =>	'Guavatá']);
        City::create(['department_id' =>	27, 'name' =>	'Güepsa']);
        City::create(['department_id' =>	27, 'name' =>	'Hato']);
        City::create(['department_id' =>	27, 'name' =>	'Jesús María']);
        City::create(['department_id' =>	27, 'name' =>	'Jordán']);
        City::create(['department_id' =>	27, 'name' =>	'La Belleza']);
        City::create(['department_id' =>	27, 'name' =>	'Landázuri']);
        City::create(['department_id' =>	27, 'name' =>	'La Paz']);
        City::create(['department_id' =>	27, 'name' =>	'Lebríja']);
        City::create(['department_id' =>	27, 'name' =>	'Los Santos']);
        City::create(['department_id' =>	27, 'name' =>	'Macaravita']);
        City::create(['department_id' =>	27, 'name' =>	'Málaga']);
        City::create(['department_id' =>	27, 'name' =>	'Matanza']);
        City::create(['department_id' =>	27, 'name' =>	'Mogotes']);
        City::create(['department_id' =>	27, 'name' =>	'Molagavita']);
        City::create(['department_id' =>	27, 'name' =>	'Ocamonte']);
        City::create(['department_id' =>	27, 'name' =>	'Oiba']);
        City::create(['department_id' =>	27, 'name' =>	'Onzaga']);
        City::create(['department_id' =>	27, 'name' =>	'Palmar']);
        City::create(['department_id' =>	27, 'name' =>	'Palmas del Socorro']);
        City::create(['department_id' =>	27, 'name' =>	'Páramo']);
        City::create(['department_id' =>	27, 'name' =>	'Piedecuesta']);
        City::create(['department_id' =>	27, 'name' =>	'Pinchote']);
        City::create(['department_id' =>	27, 'name' =>	'Puente Nacional']);
        City::create(['department_id' =>	27, 'name' =>	'Puerto Parra']);
        City::create(['department_id' =>	27, 'name' =>	'Puerto Wilches']);
        City::create(['department_id' =>	27, 'name' =>	'Rionegro']);
        City::create(['department_id' =>	27, 'name' =>	'Sabana de Torres']);
        City::create(['department_id' =>	27, 'name' =>	'San Andrés']);
        City::create(['department_id' =>	27, 'name' =>	'San Benito']);
        City::create(['department_id' =>	27, 'name' =>	'San Gil']);
        City::create(['department_id' =>	27, 'name' =>	'San Joaquín']);
        City::create(['department_id' =>	27, 'name' =>	'San José de Miranda']);
        City::create(['department_id' =>	27, 'name' =>	'San Miguel']);
        City::create(['department_id' =>	27, 'name' =>	'San Vicente de Chucurí']);
        City::create(['department_id' =>	27, 'name' =>	'Santa Bárbara']);
        City::create(['department_id' =>	27, 'name' =>	'Santa Helena del Opón']);
        City::create(['department_id' =>	27, 'name' =>	'Simacota']);
        City::create(['department_id' =>	27, 'name' =>	'Socorro']);
        City::create(['department_id' =>	27, 'name' =>	'Suaita']);
        City::create(['department_id' =>	27, 'name' =>	'Sucre']);
        City::create(['department_id' =>	27, 'name' =>	'Suratá']);
        City::create(['department_id' =>	27, 'name' =>	'Tona']);
        City::create(['department_id' =>	27, 'name' =>	'Valle de San José']);
        City::create(['department_id' =>	27, 'name' =>	'Vélez']);
        City::create(['department_id' =>	27, 'name' =>	'Vetas']);
        City::create(['department_id' =>	27, 'name' =>	'Villanueva']);
        City::create(['department_id' =>	27, 'name' =>	'Zapatoca']);
        City::create(['department_id' =>	28, 'name' =>	'Sincelejo']);
        City::create(['department_id' =>	28, 'name' =>	'Buenavista']);
        City::create(['department_id' =>	28, 'name' =>	'Caimito']);
        City::create(['department_id' =>	28, 'name' =>	'Coloso']);
        City::create(['department_id' =>	28, 'name' =>	'Corozal']);
        City::create(['department_id' =>	28, 'name' =>	'Coveñas']);
        City::create(['department_id' =>	28, 'name' =>	'Chalán']);
        City::create(['department_id' =>	28, 'name' =>	'El Roble']);
        City::create(['department_id' =>	28, 'name' =>	'Galeras']);
        City::create(['department_id' =>	28, 'name' =>	'Guaranda']);
        City::create(['department_id' =>	28, 'name' =>	'La Unión']);
        City::create(['department_id' =>	28, 'name' =>	'Los Palmitos']);
        City::create(['department_id' =>	28, 'name' =>	'Majagual']);
        City::create(['department_id' =>	28, 'name' =>	'Morroa']);
        City::create(['department_id' =>	28, 'name' =>	'Ovejas']);
        City::create(['department_id' =>	28, 'name' =>	'Palmito']);
        City::create(['department_id' =>	28, 'name' =>	'Sampués']);
        City::create(['department_id' =>	28, 'name' =>	'San Benito Abad']);
        City::create(['department_id' =>	28, 'name' =>	'San Juan de Betulia']);
        City::create(['department_id' =>	28, 'name' =>	'San Marcos']);
        City::create(['department_id' =>	28, 'name' =>	'San Onofre']);
        City::create(['department_id' =>	28, 'name' =>	'San Pedro']);
        City::create(['department_id' =>	28, 'name' =>	'San Luis de Sincé']);
        City::create(['department_id' =>	28, 'name' =>	'Sucre']);
        City::create(['department_id' =>	28, 'name' =>	'Santiago de Tolú']);
        City::create(['department_id' =>	28, 'name' =>	'Tolú Viejo']);
        City::create(['department_id' =>	29, 'name' =>	'Ibagué']);
        City::create(['department_id' =>	29, 'name' =>	'Alpujarra']);
        City::create(['department_id' =>	29, 'name' =>	'Alvarado']);
        City::create(['department_id' =>	29, 'name' =>	'Ambalema']);
        City::create(['department_id' =>	29, 'name' =>	'Anzoátegui']);
        City::create(['department_id' =>	29, 'name' =>	'Armero']);
        City::create(['department_id' =>	29, 'name' =>	'Ataco']);
        City::create(['department_id' =>	29, 'name' =>	'Cajamarca']);
        City::create(['department_id' =>	29, 'name' =>	'Carmen de Apicalá']);
        City::create(['department_id' =>	29, 'name' =>	'Casabianca']);
        City::create(['department_id' =>	29, 'name' =>	'Chaparral']);
        City::create(['department_id' =>	29, 'name' =>	'Coello']);
        City::create(['department_id' =>	29, 'name' =>	'Coyaima']);
        City::create(['department_id' =>	29, 'name' =>	'Cunday']);
        City::create(['department_id' =>	29, 'name' =>	'Dolores']);
        City::create(['department_id' =>	29, 'name' =>	'Espinal']);
        City::create(['department_id' =>	29, 'name' =>	'Falan']);
        City::create(['department_id' =>	29, 'name' =>	'Flandes']);
        City::create(['department_id' =>	29, 'name' =>	'Fresno']);
        City::create(['department_id' =>	29, 'name' =>	'Guamo']);
        City::create(['department_id' =>	29, 'name' =>	'Herveo']);
        City::create(['department_id' =>	29, 'name' =>	'Honda']);
        City::create(['department_id' =>	29, 'name' =>	'Icononzo']);
        City::create(['department_id' =>	29, 'name' =>	'Lérida']);
        City::create(['department_id' =>	29, 'name' =>	'Líbano']);
        City::create(['department_id' =>	29, 'name' =>	'Mariquita']);
        City::create(['department_id' =>	29, 'name' =>	'Melgar']);
        City::create(['department_id' =>	29, 'name' =>	'Murillo']);
        City::create(['department_id' =>	29, 'name' =>	'Natagaima']);
        City::create(['department_id' =>	29, 'name' =>	'Ortega']);
        City::create(['department_id' =>	29, 'name' =>	'Palocabildo']);
        City::create(['department_id' =>	29, 'name' =>	'Piedras']);
        City::create(['department_id' =>	29, 'name' =>	'Planadas']);
        City::create(['department_id' =>	29, 'name' =>	'Prado']);
        City::create(['department_id' =>	29, 'name' =>	'Purificación']);
        City::create(['department_id' =>	29, 'name' =>	'Rioblanco']);
        City::create(['department_id' =>	29, 'name' =>	'Roncesvalles']);
        City::create(['department_id' =>	29, 'name' =>	'Rovira']);
        City::create(['department_id' =>	29, 'name' =>	'Saldaña']);
        City::create(['department_id' =>	29, 'name' =>	'San Antonio']);
        City::create(['department_id' =>	29, 'name' =>	'San Luis']);
        City::create(['department_id' =>	29, 'name' =>	'Santa Isabel']);
        City::create(['department_id' =>	29, 'name' =>	'Suárez']);
        City::create(['department_id' =>	29, 'name' =>	'Valle de San Juan']);
        City::create(['department_id' =>	29, 'name' =>	'Venadillo']);
        City::create(['department_id' =>	29, 'name' =>	'Villahermosa']);
        City::create(['department_id' =>	29, 'name' =>	'Villarrica']);
        City::create(['department_id' =>	30, 'name' =>	'Cali']);
        City::create(['department_id' =>	30, 'name' =>	'Alcalá']);
        City::create(['department_id' =>	30, 'name' =>	'Andalucía']);
        City::create(['department_id' =>	30, 'name' =>	'Ansermanuevo']);
        City::create(['department_id' =>	30, 'name' =>	'Argelia']);
        City::create(['department_id' =>	30, 'name' =>	'Bolívar']);
        City::create(['department_id' =>	30, 'name' =>	'Buenaventura']);
        City::create(['department_id' =>	30, 'name' =>	'Guadalajara de Buga']);
        City::create(['department_id' =>	30, 'name' =>	'Bugalagrande']);
        City::create(['department_id' =>	30, 'name' =>	'Caicedonia']);
        City::create(['department_id' =>	30, 'name' =>	'Calima']);
        City::create(['department_id' =>	30, 'name' =>	'Candelaria']);
        City::create(['department_id' =>	30, 'name' =>	'Cartago']);
        City::create(['department_id' =>	30, 'name' =>	'Dagua']);
        City::create(['department_id' =>	30, 'name' =>	'El Águila']);
        City::create(['department_id' =>	30, 'name' =>	'El Cairo']);
        City::create(['department_id' =>	30, 'name' =>	'El Cerrito']);
        City::create(['department_id' =>	30, 'name' =>	'El Dovio']);
        City::create(['department_id' =>	30, 'name' =>	'Florida']);
        City::create(['department_id' =>	30, 'name' =>	'Ginebra']);
        City::create(['department_id' =>	30, 'name' =>	'Guacarí']);
        City::create(['department_id' =>	30, 'name' =>	'Jamundí']);
        City::create(['department_id' =>	30, 'name' =>	'La Cumbre']);
        City::create(['department_id' =>	30, 'name' =>	'La Unión']);
        City::create(['department_id' =>	30, 'name' =>	'La Victoria']);
        City::create(['department_id' =>	30, 'name' =>	'Obando']);
        City::create(['department_id' =>	30, 'name' =>	'Palmira']);
        City::create(['department_id' =>	30, 'name' =>	'Pradera']);
        City::create(['department_id' =>	30, 'name' =>	'Restrepo']);
        City::create(['department_id' =>	30, 'name' =>	'Riofrío']);
        City::create(['department_id' =>	30, 'name' =>	'Roldanillo']);
        City::create(['department_id' =>	30, 'name' =>	'San Pedro']);
        City::create(['department_id' =>	30, 'name' =>	'Sevilla']);
        City::create(['department_id' =>	30, 'name' =>	'Toro']);
        City::create(['department_id' =>	30, 'name' =>	'Trujillo']);
        City::create(['department_id' =>	30, 'name' =>	'Tuluá']);
        City::create(['department_id' =>	30, 'name' =>	'Ulloa']);
        City::create(['department_id' =>	30, 'name' =>	'Versalles']);
        City::create(['department_id' =>	30, 'name' =>	'Vijes']);
        City::create(['department_id' =>	30, 'name' =>	'Yotoco']);
        City::create(['department_id' =>	30, 'name' =>	'Yumbo']);
        City::create(['department_id' =>	30, 'name' =>	'Zarzal']);
        City::create(['department_id' =>	3, 'name' =>	'Arauca']);
        City::create(['department_id' =>	3, 'name' =>	'Arauquita']);
        City::create(['department_id' =>	3, 'name' =>	'Cravo Norte']);
        City::create(['department_id' =>	3, 'name' =>	'Fortul']);
        City::create(['department_id' =>	3, 'name' =>	'Puerto Rondón']);
        City::create(['department_id' =>	3, 'name' =>	'Saravena']);
        City::create(['department_id' =>	3, 'name' =>	'Tame']);
        City::create(['department_id' =>	9, 'name' =>	'Yopal']);
        City::create(['department_id' =>	9, 'name' =>	'Aguazul']);
        City::create(['department_id' =>	9, 'name' =>	'Chameza']);
        City::create(['department_id' =>	9, 'name' =>	'Hato Corozal']);
        City::create(['department_id' =>	9, 'name' =>	'La Salina']);
        City::create(['department_id' =>	9, 'name' =>	'Maní']);
        City::create(['department_id' =>	9, 'name' =>	'Monterrey']);
        City::create(['department_id' =>	9, 'name' =>	'Nunchía']);
        City::create(['department_id' =>	9, 'name' =>	'Orocué']);
        City::create(['department_id' =>	9, 'name' =>	'Paz de Ariporo']);
        City::create(['department_id' =>	9, 'name' =>	'Pore']);
        City::create(['department_id' =>	9, 'name' =>	'Recetor']);
        City::create(['department_id' =>	9, 'name' =>	'Sabanalarga']);
        City::create(['department_id' =>	9, 'name' =>	'Sácama']);
        City::create(['department_id' =>	9, 'name' =>	'San Luis de Palenque']);
        City::create(['department_id' =>	9, 'name' =>	'Támara']);
        City::create(['department_id' =>	9, 'name' =>	'Tauramena']);
        City::create(['department_id' =>	9, 'name' =>	'Trinidad']);
        City::create(['department_id' =>	9, 'name' =>	'Villanueva']);
        City::create(['department_id' =>	23, 'name' =>	'Mocoa']);
        City::create(['department_id' =>	23, 'name' =>	'Colón']);
        City::create(['department_id' =>	23, 'name' =>	'Orito']);
        City::create(['department_id' =>	23, 'name' =>	'Puerto Asís']);
        City::create(['department_id' =>	23, 'name' =>	'Puerto Caicedo']);
        City::create(['department_id' =>	23, 'name' =>	'Puerto Guzmán']);
        City::create(['department_id' =>	23, 'name' =>	'Leguízamo']);
        City::create(['department_id' =>	23, 'name' =>	'Sibundoy']);
        City::create(['department_id' =>	23, 'name' =>	'San Francisco']);
        City::create(['department_id' =>	23, 'name' =>	'San Miguel']);
        City::create(['department_id' =>	23, 'name' =>	'Santiago']);
        City::create(['department_id' =>	23, 'name' =>	'Valle del Guamuez']);
        City::create(['department_id' =>	23, 'name' =>	'Villagarzón']);
        City::create(['department_id' =>	26, 'name' =>	'San Andrés']);
        City::create(['department_id' =>	26, 'name' =>	'Providencia']);
        City::create(['department_id' =>	1, 'name' =>	'Leticia']);
        City::create(['department_id' =>	1, 'name' =>	'El Encanto']);
        City::create(['department_id' =>	1, 'name' =>	'La Chorrera']);
        City::create(['department_id' =>	1, 'name' =>	'La Pedrera']);
        City::create(['department_id' =>	1, 'name' =>	'La Victoria']);
        City::create(['department_id' =>	1, 'name' =>	'Miriti - Paraná']);
        City::create(['department_id' =>	1, 'name' =>	'Puerto Alegría']);
        City::create(['department_id' =>	1, 'name' =>	'Puerto Arica']);
        City::create(['department_id' =>	1, 'name' =>	'Puerto Nariño']);
        City::create(['department_id' =>	1, 'name' =>	'Puerto Santander']);
        City::create(['department_id' =>	1, 'name' =>	'Tarapacá']);
        City::create(['department_id' =>	15, 'name' =>	'Inírida']);
        City::create(['department_id' =>	15, 'name' =>	'Barranco Minas']);
        City::create(['department_id' =>	15, 'name' =>	'Mapiripana']);
        City::create(['department_id' =>	16, 'name' =>	'San José del Guaviare']);
        City::create(['department_id' =>	16, 'name' =>	'Calamar']);
        City::create(['department_id' =>	16, 'name' =>	'El Retorno']);
        City::create(['department_id' =>	16, 'name' =>	'Miraflores']);
        City::create(['department_id' =>	31, 'name' =>	'Mitú']);
        City::create(['department_id' =>	31, 'name' =>	'Caruru']);
        City::create(['department_id' =>	31, 'name' =>	'Taraira']);
        City::create(['department_id' =>	32, 'name' =>	'Puerto Carreño']);
        City::create(['department_id' =>	32, 'name' =>	'La Primavera']);
        City::create(['department_id' =>	32, 'name' =>	'Santa Rosalía']);
        City::create(['department_id' =>	32, 'name' =>	'Cumaribo']);
    }
}
